/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccButton: typeof import('./src/components/kits/AccButton.vue')['default']
    Ani: typeof import('./src/components/kits/Ani.vue')['default']
    AwsomeButton: typeof import('./src/components/kits/AwsomeButton.vue')['default']
    BookShelf: typeof import('./src/components/BookShelf.vue')['default']
    BookSpine: typeof import('./src/components/BookSpine.vue')['default']
    ClickOutside: typeof import('./src/components/kits/ClickOutside.vue')['default']
    Contents: typeof import('./src/components/Contents.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    CustomCursor: typeof import('./src/components/kits/CustomCursor.vue')['default']
    CustomModal: typeof import('./src/components/CustomModal.vue')['default']
    Detail: typeof import('./src/components/Detail.vue')['default']
    Icon: typeof import('./src/components/kits/icon/Icon.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    Loading: typeof import('./src/components/kits/Loading.vue')['default']
    MenuItem: typeof import('./src/components/menu/MenuItem.vue')['default']
    Mouse: typeof import('./src/components/kits/Mouse.vue')['default']
    ProgressBar: typeof import('./src/components/kits/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopMenu: typeof import('./src/components/menu/TopMenu.vue')['default']
  }
}
